### ISSUE TITLE
Fails to start because of syntax error

### ISSUE THREAD

**Issue by Knusper** [ManrajGrover/football-cli#5]
All I get after installing with npm is. 

Input: `football`

Output:

```
const updateMessage = (TYPE, message = "") => {
                                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/knusper/.npm-packages/lib/node_modules/footballcli/cli.js:22:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by ManrajGrover** [comment]
@Knusper Hey! Thank you for reporting this issue. This must be fixed now. Please confirm by updating the package. Reason was this functionality hasn't been introduced in version Node Version 4.4.7.  

Also, this issue was closed automatically due to reference.

**Comment by Knusper** [comment]
Thanks. Yes. Works now :dancer:
